version: '3.8'

services:
  lait-app:
    build: .
    ports:
      - "5003:5003"
    environment:
      - FLASK_APP=backend/app_real.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/legalspend
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=development-key-change-in-production
      - JWT_SECRET_KEY=jwt-dev-key-change-in-production
    volumes:
      - ./backend/logs:/app/backend/logs
      - ./backend/uploads:/app/backend/uploads
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=legalspend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery-worker:
    build: .
    command: celery -A backend.celery_worker.celery worker --loglevel=info
    environment:
      - FLASK_APP=backend/app_real.py
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/legalspend
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
