# LAIT Platform - Render.com Deployment Blueprint
# ==============================================
#
# This render.yaml file defines the complete infrastructure for the LAIT 
# Legal Intelligence Platform deployment on Render.com:
# - PostgreSQL database for data persistence
# - Redis instance for caching and session management  
# - Backend API service with Gunicorn WSGI server
# - Frontend static site with React SPA
# - Environment variable configuration for production

services:
  # Backend API Service
  - type: web
    name: lait-api
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      echo "🔧 Installing backend dependencies..."
      cd backend && pip install --no-cache-dir -r requirements.txt
      echo "✅ Backend build complete"
    startCommand: |
      cd backend && ./start_gunicorn.sh
    dockerfilePath: ./backend/Dockerfile.prod
    disk:
      name: lait-api-disk
      size: 1GB
      mount: /app/uploads
    healthCheckPath: /api/health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "false"
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: lait-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: lait-redis
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: "https://lait-web.onrender.com,http://localhost:3000"
      - key: UPLOAD_FOLDER
        value: "/app/uploads"
      - key: MAX_CONTENT_LENGTH
        value: "16777216"  # 16MB
      - key: RATE_LIMIT_STORAGE_URL
        fromService:
          type: redis
          name: lait-redis
          property: connectionString

  # Frontend Static Site
  - type: static
    name: lait-web
    buildCommand: |
      echo "🔧 Building frontend..."
      cd frontend
      npm ci --silent
      npm run build
      echo "✅ Frontend build complete - ready for deployment"
    staticPublishPath: ./frontend/dist
    pullRequestPreviewsEnabled: true
    buildFilter:
      paths:
      - frontend/**
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-XSS-Protection  
        value: 1; mode=block
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE
        value: https://lait-api.onrender.com
      - key: NODE_ENV
        value: production

databases:
  # PostgreSQL Primary Database
  - name: lait-postgres
    databaseName: lait_production
    user: lait_user
    region: oregon
    plan: starter
    postgresMajorVersion: 15

  # Redis Cache & Session Store
  - name: lait-redis
    region: oregon
    plan: starter
    maxmemoryPolicy: allkeys-lru
