version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: lait_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lait
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7
    container_name: lait_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # LAIT API Backend
  api:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: lait_api
    ports:
      - "5003:5003"
    env_file:
      - ../.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lait
      - REDIS_URL=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../backend:/app/backend
      - ../ml:/app/ml
    restart: unless-stopped

  # Frontend Web Application
  web:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: lait_web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:5003
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
