"""add notification read_at and indexes

Revision ID: 70b3762d9adc
Revises: 4a5f0287b26c
Create Date: 2025-08-10 04:19:36.182963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b3762d9adc'
down_revision = '4a5f0287b26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_notifications_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_notifications_user_unread', ['user_id', 'read'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_unread')
        batch_op.drop_index('ix_notifications_created_at')
        batch_op.drop_column('read_at')

    # ### end Alembic commands ###
